version: '3.8'

services:
  app:
    build: .
    container_name: rag-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=PROD
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run prod
